asset_management/urls.py
from django.urls import path
from .views.asset_views import AllAssets, CreateAsset, UpdateAsset, AllocateAsset
from .views.assetgroup_views import (
    AssetGroupCreateView,
    AssetGroupUpdateView,
    AssetGroupDeleteView,
    AssetGroupReportView,
    AssetGroupListView,
)


urlpatterns = [
    path("asset/list", AllAssets.as_view(), name="assets"),
    path("asset/new", CreateAsset.as_view(), name="add_new_asset"),
    path("asset/<int:pk>/edit", UpdateAsset.as_view(), name="update_asset"),
    path("asset/<int:pk>/allocate", AllocateAsset.as_view(), name="allocate_asset"),
]


urlpatterns += [
    path("assetgroup/new/", AssetGroupCreateView.as_view(), name="AssetGroup-create"),
    path(
        "assetgroup/<int:pk>/edit/",
        AssetGroupUpdateView.as_view(),
        name="AssetGroup-update",
    ),
    path(
        "assetgroup/<int:pk>/delete/",
        AssetGroupDeleteView.as_view(),
        name="AssetGroup-delete",
    ),
    path("assetgroup/list/", AssetGroupListView.as_view(), name="AssetGroup-list"),
    path(
        "assetgroup/report/", AssetGroupReportView.as_view(), name="AssetGroup-report"
    ),
    path("", AssetGroupReportView.as_view(), name="Welcome"),
]

assetmanagement/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("asset_management.urls")),
]

asset_management/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse


class AssetGroup(models.Model):
    name = models.CharField(max_length=128, blank=False, unique=True)
    description = models.CharField(max_length=255, default="", null=True, blank=True)
    cable_count = models.IntegerField(default=0, null=False, blank=False)

    class Meta:
        verbose_name = "Asset Group"
        verbose_name_plural = "Asset Groups"

    def __str__(self):
        return f"{self.name}"


class Asset(models.Model):
    CHOICES = (
        ("OPERATIONAL", "Operational"),
        ("NONOPERATIONAL", "Nonoperational"),
        ("MISSING", "Missing"),
    )

    name = models.CharField(max_length=128, blank=False)
    description = models.CharField(max_length=255, default="", null=True, blank=True)
    asset_code = models.CharField(max_length=128, blank=False, unique=True)
    asset_group = models.ForeignKey(
        AssetGroup, related_name="assets", on_delete=models.CASCADE
    )
    asset_model_number = models.CharField(max_length=128, null=False, blank=False)
    asset_serial_number = models.CharField(
        max_length=128, default="", blank=True, null=True
    )
    asset_purchase_date = models.DateTimeField(default=timezone.now)
    modified_on = models.DateTimeField(auto_now=True)
    status = models.CharField(choices=CHOICES, default="OPERATIONAL", max_length=128)

    class Meta:
        verbose_name = "Asset"
        verbose_name_plural = "Assets"

    def __str__(self):
        return f"{self.name} - {self.asset_code}"

    def get_absolute_url(self):
        return reverse("assets")


class AssetAllocation(models.Model):
    asset = models.OneToOneField(
        Asset, on_delete=models.CASCADE, related_name="allocations"
    )
    employee_name = models.CharField(max_length=255, default="Office")

    class Meta:
        verbose_name = "Asset Allocation"
        verbose_name_plural = "Asset Allocations"

    def __str__(self) -> str:
        return f"{self.employee_name} : {self.asset}"

    def get_absolute_url(self):
        return reverse("update_asset", kwargs={"pk": self.asset.id})

asset_management/views/asset_views.py
from math import ceil
from django.shortcuts import get_object_or_404
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic import ListView
from ..models import Asset, AssetAllocation


class CreateAsset(CreateView):
    template_name = "addAsset.html"
    model = Asset
    fields = [
        "name",
        "description",
        "asset_code",
        "asset_group",
        "asset_model_number",
        "asset_serial_number",
    ]


class UpdateAsset(UpdateView):
    template_name = "updateAsset.html"
    model = Asset
    fields = [
        "name",
        "description",
        "asset_code",
        "asset_group",
        "asset_model_number",
        "asset_serial_number",
        "status",
    ]


class AllAssets(ListView):
    template_name = "assets.html"
    context_object_name = "assets"
    paginate_by = 30

    def get_queryset(self):
        return Asset.objects.all()

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)

        page_number = int(self.request.GET.get("page", 1))
        context["page_number"] = page_number
        records_per_page = self.paginate_by
        total_records = len(Asset.objects.all())
        context["last"] = ceil(total_records / records_per_page)
        remaining_records = total_records - ((page_number - 1) * records_per_page)
        context["has_more_records"] = remaining_records > records_per_page
        return context


class AllocateAsset(UpdateView):
    template_name = "asset_allocate.html"
    model = AssetAllocation
    fields = "__all__"

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()
        asset = get_object_or_404(queryset, asset_id=self.kwargs["pk"])
        return asset

asset_management/views/assetgroup_views.py
# views.py
from django.urls import reverse_lazy
from django.views import View
from django.shortcuts import render
from django.views.generic import CreateView, UpdateView, DeleteView, ListView
from ..models import AssetGroup


class AssetGroupCreateView(CreateView):
    model = AssetGroup
    template_name = "assetgroup_form.html"
    fields = "__all__"
    success_url = reverse_lazy("AssetGroup-report")


class AssetGroupUpdateView(UpdateView):
    model = AssetGroup
    template_name = "assetgroup_form.html"
    fields = "__all__"
    success_url = reverse_lazy("AssetGroup-report")


class AssetGroupDeleteView(DeleteView):
    model = AssetGroup
    template_name = "assetgroup_confirm_delete.html"
    success_url = reverse_lazy("AssetGroup-report")


class AssetGroupListView(ListView):
    model = AssetGroup
    template_name = "assetgroup_list.html"
    context_object_name = "AssetGroup_list"
    ordering = ["-id"]


class AssetGroupReportView(View):
    template_name = "assetgroup_report.html"

    def get(self, request, *args, **kwargs):
        asset_groups = AssetGroup.objects.prefetch_related("assets__allocations").all()

        context = {"asset_groups": asset_groups}
        return render(request, self.template_name, context)

asset_management/templates/AsetGroup_confirm_delete.html
{% block content %}
  <h2>Delete Your Model</h2>
  <p>Are you sure you want to delete "{{ object }}"?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Confirm</button>
  </form>
{% endblock %}

asset_management/templates/AssetGroup_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
  <h2>Delete Asset Group</h2>
  <p>Are you sure you want to delete "{{ object }}"?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Confirm</button>
  </form>
{% endblock %}

asset_management/templates/AssetGroup_list.html
{% extends 'base.html' %}
{% block content %}
  <h2>Asset Group List</h2>
  <ul>
    {% for AssetGroup in AssetGroup_list %}
      <li>{{ AssetGroup.name }} - {{ AssetGroup.description }}</li>
    {% endfor %}
  </ul>
{% endblock %}

asset_management/templates/AssetGroup_report.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h2>Asset Group Report</h2>
{% for asset_group in asset_groups %}
<h3><a href="{% url 'AssetGroup-update' asset_group.id %}">
        {{ asset_group.name }}
    </a>

    <a href="{% url 'AssetGroup-update' asset_group.id %}"><img src="{% static '/images/edit-text.png' %}"
            style="height:20px; margin-left: 2px;" alt="Update"></a>
    <a href="{% url 'AssetGroup-delete' asset_group.id %}"><img src="{% static '/images/deleteicon.png' %}"
            style="height:20px; margin-left: 2px;" alt="Delete"></a>

</h3>
<table>
    <thead>
        <tr>
            <th>Asset Name</th>
            <th>Asset Code</th>
            <th>Asset Model Number</th>
            <th>Employee Name</th>
        </tr>
    </thead>
    <tbody>
        {% for asset in asset_group.assets.all %}
        <tr>
            <td>{{ asset.name }}</td>
            <td><a href="{% url 'update_asset' asset.id %}">{{ asset.asset_code }} </a></td>
            <td>{{ asset.asset_model_number }}</td>
            {% for allocation in asset.assetallocation_set.all %}
            <td>{{ allocation.employee_name }}</td>
            {% endfor %}
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endfor %}
{% endblock %}

asset_management/templates/addAsset.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Asset</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        {{form}}
        <button type="submit"> ADD </button>
    </form>
</body>
</html>

asset_management/templates/asset_allocate.html
{% extends 'base.html' %}
{% block content %}
    <h2>Add Asset</h2>

    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit"> Allocate </button>
    </form>
{% endblock %}

asset_management/templates/assetgroup_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
  <h2>Delete Asset Group</h2>
  <p>Are you sure you want to delete "{{ object }}"?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Confirm</button>
  </form>
{% endblock %}

asset_management/templates/assetgroup_form.html
{% extends 'base.html' %}

{% block content %}
  <h2>Add Asset Group</h2>
  <form method="post">
    {% csrf_token %}
    {{form}}
    <button type="submit">{% if object %}Update{% else %}Create{% endif %}</button>
  </form>
{% endblock %}

asset_management/templates/assetgroup_list.html
{% extends 'base.html' %}
{% block content %}
  <h2>Asset Group List</h2>
  <ul>
    {% for AssetGroup in AssetGroup_list %}
      <li>{{ AssetGroup.name }} - {{ AssetGroup.description }}</li>
    {% endfor %}
  </ul>
{% endblock %}

asset_management/templates/assetgroup_report.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h2>Asset Group Report</h2>
{% for asset_group in asset_groups %}
<h3>
    {{ asset_group.name }}
    <a href="{% url 'AssetGroup-update' asset_group.id %}"><img src="{% static '/images/edit-text.png' %}"
            style="height:20px; margin-left: 2px;" alt="Update" title="Update Asset Group"></a>
    <a href="{% url 'AssetGroup-delete' asset_group.id %}"><img src="{% static '/images/deleteicon.png' %}"
            style="height:20px; margin-left: 2px;" alt="Delete" title="Delete Asset Group"></a>

</h3>
<table>
    <thead>
        <tr>
            <th>Asset Name</th>
            <th>Asset Code</th>
            <th>Asset Model Number</th>
            <th>Asset Status</th>
            <th>Employee Name</th>
        </tr>
    </thead>
    <tbody>
        {% for asset in asset_group.assets.all %}
        <tr>
            <td>{{ asset.name }}</td>
            <td>
                <span style="float: left;">{{ asset.asset_code }}</span>
                <span style="float: right;"><a href="{% url 'update_asset' asset.id %}"><img
                            src="{% static '/images/edit-text.png' %}" style="height:20px; margin-left: 2px;"
                            alt="Update" title="Update/Delete Asset"></a></span>
            </td>
            <td>{{ asset.asset_model_number }}</td>
            <td class="change-color">{{ asset.status}}</td>
            <td>
                {% if asset.allocations %}
                {{asset.allocations.employee_name}}
                <span style="float: right;"><a href="{% url 'allocate_asset' asset.id %}"><img
                            src="{% static '/images/edit-text.png' %}" style="height:20px; margin-left: 2px;"
                            alt="Update" title="Update Asset Allocation"></a></span>
                {% else %}
                Office
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endfor %}
{% endblock %}

asset_management/templates/assets.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <table>
        <thead>
            <tr>
                <th>Asset Code</th>
                <th>Asset name</th>
                <th>Asset Status</th>
            </tr>
        </thead>
        <tbody>
            {% for asset in assets %}
            <tr>
                <td>
                    <span style="float: left;">{{asset.asset_code}}</span>
                    <span style="float: right;"><a href="{% url 'update_asset' asset.id %}"><img
                        src="{% static '/images/edit-text.png' %}" style="height:20px; margin-left: 2px;"
                        alt="Update" title="Update/Delete Asset"></a></span>
                </td>
                <td>{{asset.name}}</td>
                <td class="change-color">{{asset.status}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <div style="margin-top: 20px;">
        <a href="{% url 'add_new_asset' %}">
            <button>Add New Asset</button>
        </a>
    </div>

    <br><br>
    <div class="pagination">
        <span class="step-links">
            {% if page_number > 1 %}
                &laquo; <a href="?page=1">First</a>
                <a href="?page={{ page_number|add:'-1' }}">Prev</a>
            {% endif %}
    
            <span class="current-page">{{ page_number }}</span>
    
            {% if has_more_records %}
                <a href="?page={{ page_number|add:'1' }}">Next</a>
                <a href="?page={{last}}">Last</a> &raquo;
            {% endif %}

            
        </span>
    </div>

{% endblock %}

asset_management/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Asset Management{% endblock %}</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            margin: 0;
            padding: 0;
        }

        img {
            height: auto;
            max-width: 100%;
        }

        #navbar {
            height: 100%;
            width: 250px;
            position: fixed;
            z-index: 1;
            top: 0;
            left: 0;
            background-color: #111;
            overflow-x: hidden;
            padding-top: 20px;
            transition: 0.5s;
        }

        #navbar a {
            padding: 15px;
            text-decoration: none;
            font-size: 18px;
            color: #818181;
            display: block;
            transition: 0.3s;
        }

        #navbar h1 {
            padding: 15px;
            text-decoration: none;
            font-size: 24px;
            color: #818181;
            display: block;
            transition: 0.3s;
        }

        #navbar a:hover {
            color: #f1f1f1;
        }

        #navbar .closebtn {
            position: absolute;
            top: 0;
            right: 25px;
            font-size: 24px;
            margin-left: 50px;
            margin-bottom: 10px;
        }

        #main {
            transition: margin-left 0.5s;
            padding: 16px;
            margin-left: 250px;
        }

        table,
        th,
        td {
            border: 1px solid black;
        }
    </style>
</head>

<body>

    <div id="navbar" >
        <div> <h1>Menu</h1> </div>
        <div><a href="{% url 'AssetGroup-report' %}">Asset Group Report</a></div>

        <div><a href="{% url 'AssetGroup-create' %}">Create Asset Group</a></div>

        <a href="{% url 'assets' %}">Asset Report</a>

        <a href="{% url 'add_new_asset' %}">Add New Asset</a>


    </div>

    <div id="main">

        {% block content %}{% endblock %}
    </div>



</body>
<script>
    var cells = document.getElementsByClassName('change-color');

    for (var i = 0; i < cells.length; i++) {
        var cellValue = cells[i].innerText;

        if (cellValue === 'OPERATIONAL') {
            cells[i].style.backgroundColor = 'lightgreen';
        } else  {
            cells[i].style.backgroundColor = '#ff5050';
        }
    }
</script>

</html>

asset_management/templates/updateAsset.html
{% extends 'base.html' %}

{% block content %}

    <h2>Update Asset</h2>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <br>
        <button type="submit"> UPDATE </button>
    </form>

    <br>
    <a href="{% url 'allocate_asset' asset.id%}">
        Allocate this asset to a User
    </a>
{% endblock %}